<a href="https://colab.research.google.com/github/m-ony/mineria-de-datos/blob/main/Buscador_181619.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recuperación de Información

Monica Hernandez Quiroz - 181619

In [41]:
import os
import nltk
import numpy as np

In [ ]:
nltk.download("stopwords")
nltk.download('punkt_tab')
from sklearn.feature_extraction.text import CountVectorizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [33]:
#Tokenizador
def tokenizar(libro):
    puntuacion = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~¿¡—–'

    # Normalizar
    libro = libro.lower()

    # Tokenizar
    tokens = nltk.word_tokenize(libro, "spanish")

    # Quitar puntuación de los extremos
    for i, token in enumerate(tokens):
        tokens[i] = token.strip(puntuacion)

    # Volver a formar texto
    texto = " ".join(tokens)

    # Tokenizar nuevamente
    tokens = nltk.word_tokenize(libro, "spanish")

    # Quedarnos solamente con palabras
    tokens = [
        token for token in tokens
        if token.isalpha()]
    return tokens

In [34]:
#Stop Words
palabras_funcionales=nltk.corpus.stopwords.words("spanish")
print(palabras_funcionales)

['de', 'la', 'que', 'el', 'en', 'y', 'a', 'los', 'del', 'se', 'las', 'por', 'un', 'para', 'con', 'no', 'una', 'su', 'al', 'lo', 'como', 'más', 'pero', 'sus', 'le', 'ya', 'o', 'este', 'sí', 'porque', 'esta', 'entre', 'cuando', 'muy', 'sin', 'sobre', 'también', 'me', 'hasta', 'hay', 'donde', 'quien', 'desde', 'todo', 'nos', 'durante', 'todos', 'uno', 'les', 'ni', 'contra', 'otros', 'ese', 'eso', 'ante', 'ellos', 'e', 'esto', 'mí', 'antes', 'algunos', 'qué', 'unos', 'yo', 'otro', 'otras', 'otra', 'él', 'tanto', 'esa', 'estos', 'mucho', 'quienes', 'nada', 'muchos', 'cual', 'poco', 'ella', 'estar', 'estas', 'algunas', 'algo', 'nosotros', 'mi', 'mis', 'tú', 'te', 'ti', 'tu', 'tus', 'ellas', 'nosotras', 'vosotros', 'vosotras', 'os', 'mío', 'mía', 'míos', 'mías', 'tuyo', 'tuya', 'tuyos', 'tuyas', 'suyo', 'suya', 'suyos', 'suyas', 'nuestro', 'nuestra', 'nuestros', 'nuestras', 'vuestro', 'vuestra', 'vuestros', 'vuestras', 'esos', 'esas', 'estoy', 'estás', 'está', 'estamos', 'estáis', 'están', 'e

In [37]:
vocabulario = vectorizador.get_feature_names_out()
vocabulario

array(['ab', 'abad', 'abadejo', ..., 'úsese', 'útil', 'útiles'],
      dtype=object)

TF = frecuencia de la palabra \​ total de palabras del libro




In [57]:
#Matriz TF - Frecuancia de aparición en el documento
def tf(matriz_frecuencias):
  matriz_tf = matriz_frecuencias.toarray().astype(float) # asigan los valores de la matriz de frecuencia y cambia a flotantes

  for i in range(matriz_tf.shape[0]): # for para recorrer la matriz tf

      total_palabras = matriz_tf[i].sum()  # el total de palabras en cada libro

      matriz_tf[i] = matriz_tf[i] / total_palabras
  return matriz_tf

In [58]:
#Matriz IDF - En cuantos documentos aparece la palabra
def  idf (matriz_frecuencias):
  df = np.count_nonzero(
      matriz_frecuencias.toarray() > 0,
      axis=0 #por columnas
  )

  #Nos devuelve la cantidad de libros en nuetros corpus
  #shape[0] -> numero de filas
  #shape[1] -> numero de columnas

  idf = np.log(matriz_frecuencias.shape[0] / df)
  return idf

In [59]:
def tf_idf(matriz_tf, idf):
  matriz_tfidf = matriz_tf * idf
  matriz_tfidf
  return matriz_tfidf

## Trabajando con Corpus

In [60]:
#Vector
corpus = os.listdir('/content/drive/MyDrive/IA/Corpus10')
libros = ['/content/drive/MyDrive/IA/Corpus10/'+archivo for archivo in corpus]
vectorizador = CountVectorizer(input="filename",analyzer="word",tokenizer = tokenizar, stop_words= palabras_funcionales)
matriz_frecuencias = vectorizador.fit_transform(libros)

#Mostrar la matriz que contiene cuántas veces aparece cada palabra en cada libro
matriz_frecuencias.toarray()

/usr/local/lib/python3.13/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


array([[0, 0, 0, ..., 0, 2, 1],
       [1, 3, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 2],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 5, 2, ..., 0, 4, 1]])

In [62]:
# TF de Corpus
matriz_tf = tf(matriz_frecuencias)
matriz_tf

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.13513820e-04, 5.67569102e-05],
       [1.79684833e-05, 5.39054498e-05, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 3.70699881e-05, 7.41399763e-05],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 2.78567051e-05, 1.11426820e-05, ...,
        0.00000000e+00, 2.22853641e-05, 5.57134102e-06]])

In [63]:
# IDF de Corpus
idf_corpus = idf(matriz_frecuencias)
idf_corpus

array([2.30258509, 1.60943791, 2.30258509, ..., 2.30258509, 0.91629073,
       0.91629073])

In [64]:
#Matriz TFIDF
matriz_tfidf = tf_idf(matriz_tf, idf_corpus)
matriz_tfidf

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.04011661e-04, 5.20058307e-05],
       [4.13739617e-05, 8.67574747e-05, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 3.39668866e-05, 6.79337731e-05],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 4.48336373e-05, 2.56569736e-05, ...,
        0.00000000e+00, 2.04198726e-05, 5.10496814e-06]])

##Trabajando con cadena de texto
¿Batalla de Caballero?

In [203]:

consulta="¿Batalla de Caballero?, Con su espada levantada y el escudo firme, luchó con valentía para proteger a su pueblo, convirtiéndose en símbolo de honor y coraje."

vectorizador_consulta = CountVectorizer( #con este ya normalizamos, limpiamos, tokenizamos
    tokenizer=tokenizar,
    stop_words=palabras_funcionales,
    vocabulary=vectorizador.vocabulary_, # le compartirmos el vocabulario aprendido
)

matriz_frecuencias_consulta = vectorizador_consulta.transform([consulta])

In [204]:
matriz_frecuencias_consulta.toarray()


array([[0, 0, 0, ..., 0, 0, 0]])

In [205]:
#TF de consulta
total = matriz_frecuencias_consulta.sum()

tf_consulta = matriz_frecuencias_consulta/ total
tf_consulta
tf_consulta = tf_consulta.toarray()
print(tf_consulta.shape)

(1, 47355)


In [206]:
tokens_consulta = tokenizar(consulta)
tokens_consulta = [
    palabra for palabra in tokens_consulta
    if palabra not in palabras_funcionales
]
tokens_consulta

['caballero',
 'espada',
 'levantada',
 'escudo',
 'firme',
 'luchó',
 'valentía',
 'proteger',
 'pueblo',
 'convirtiéndose',
 'símbolo',
 'honor',
 'coraje']

In [207]:
#IDF de consulta
idf_consulta = np.zeros(matriz_frecuencias.shape[1])

for palabra in tokens_consulta:
    if palabra in vectorizador.vocabulary_:
      posicion = vectorizador.vocabulary_[palabra]

      idf_consulta[posicion] = idf_corpus[posicion]

print(idf_consulta)
print(idf_consulta.shape)

[0. 0. 0. ... 0. 0. 0.]
(47355,)


In [208]:
#TFIDF de Consulta
tfidf_consulta = tf_consulta * idf_consulta
print(tfidf_consulta)
print(tfidf_consulta.shape)

[[0. 0. 0. ... 0. 0. 0.]]
(1, 47355)


In [209]:
print("Palabras diferentes de cero:",
      np.count_nonzero(tfidf_consulta))

Palabras diferentes de cero: 11


##Cacular la similitud coseno

In [210]:
#estas son nuestros dos TDIDF
#tfidf_consulta
#matriz_tfidf

In [211]:
from scipy import spatial

tfidf_consulta = tfidf_consulta.flatten()
similitudes = []
for libro in  matriz_tfidf:
  similitud = 1 - spatial.distance.cosine(tfidf_consulta, libro)
  similitudes.append(similitud)
print(similitudes)

[np.float64(0.0005739582575617908), np.float64(0.003078609049905312), np.float64(0.0), np.float64(0.0005301226778978707), np.float64(0.004161266771293359), np.float64(0.002655762353930724), np.float64(0.0019544954830518213), np.float64(0.0008141440390817545), np.float64(0.002079326832256756), np.float64(0.012799988580476152)]


In [212]:
print("Libro que estas buscando puede ser: ", corpus[similitudes.index(max(similitudes))])

Libro que estas buscando puede ser:  2000
