<a href="https://colab.research.google.com/github/m-ony/mineria-de-datos/blob/main/Miner%C3%ADa_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de Datos

##Primer Parcial

### Introducción

#### Conceptos

##### Mineria de Datos


La minería de datos es un proceso que utiliza herramientas analíticas avanzadas para extraer información útil de grandes volúmenes de datos almacenados en bases de datos. Este proceso permite identificar patrones, tendencias y relaciones que son clave para la toma de decisiones estratégicas en diversas áreas de negocio.

##### Ciencia de Datos

Es el campo integral que utiliza métodos científicos, algoritmos y sistemas para extraer conocimiento y insights de datos estructurados y no estructurados, con el objetivo de resolver problemas complejos, hacer predicciones y apoyar la toma de decisiones. Abarca todo el ciclo de vida de los datos, desde la formulación del problema y la recolección hasta el modelado avanzado, el despliegue de soluciones y la comunicación de resultados, combinando estadística, programación y conocimiento del dominio.

#### Ciencia de Datos

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
len?

In [ ]:
L= [1,2,3]

In [ ]:
L.insert?

In [ ]:
L?

In [ ]:
def square(a):
  """Return the square of a."""
  return a**2

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

In [ ]:
L.insert

<function list.insert(index, object, /)>

In [ ]:
L.count

<function list.count(value, /)>

In [ ]:
L.count

<function list.count(value, /)>

In [ ]:
L.__add__

<method-wrapper '__add__' of list object at 0x7b037982fb40>

In [ ]:
from itertools import combinations

In [ ]:
import dis

In [ ]:
*Warning?

In [1]:
# EL comando  magico  sirve para evaluar desempeño en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

88.7 µs ± 32.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [3]:
# el comandio nagico  sirve pra evaluar el desempeño, solo que este abarca en varias lineas de codigo en lugar de una
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)

75.4 µs ± 1.56 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [5]:
!ls

sample_data


In [9]:
%cd sample_data/

/content/sample_data


In [10]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [11]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [12]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '31525c8188ad',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in Python

In [13]:
import numpy as np

In [14]:
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

In [15]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [18]:

np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [17]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [19]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])