<a href="https://colab.research.google.com/github/m-ony/mineria-de-datos/blob/main/sklearn_countvectorizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Sklearn CountVectorizer




Monica Hernandez Quiroz 181619

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()
#array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
      # 'this'], ...)
print(X.toarray())
#[[0 1 1 1 0 0 1 0 1]
# [0 2 0 1 0 1 1 0 1]
# [1 0 0 1 1 0 1 1 1]
 #[0 1 1 1 0 0 1 0 1]]

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


corpus es el texto o libros que tenemos


class sklearn.feature_extraction.text.CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\b\w\w+\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)


lowercase -> todo a minusculas   
tokenizer -> se puede personalizar nuestro tokenizador y mandarlo a llamar.


##TfidfVectorizer

In [8]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
vocabulario2 = vectorizer.get_feature_names_out()
#array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
 #      'this'], ...)
print(X.shape)

tabla_tfidf = pd.DataFrame(X.toarray(), index=corpus, columns=vocabulario2)
tabla_tfidf

(4, 9)


,and,document,first,is,one,second,the,third,this
This is the first document.,0.000000,0.469791,0.580286,0.384085,0.000000,0.000000,0.384085,0.000000,0.384085
This document is the second document.,0.000000,0.687624,0.000000,0.281089,0.000000,0.538648,0.281089,0.000000,0.281089
And this is the third one.,0.511849,0.000000,0.000000,0.267104,0.511849,0.000000,0.267104,0.511849,0.267104
Is this the first document?,0.000000,0.469791,0.580286,0.384085,0.000000,0.000000,0.384085,0.000000,0.384085


Convert a collection of raw documents to a matrix of TF-IDF features.

Mientras aparesca en mas docuemntos la palabra no es tan importante.